# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/readline-ext/all/readline-ext.rbi
#
# readline-ext-0.1.2

module Readline
  def readline(*arg0); end
  def self.basic_quote_characters; end
  def self.basic_quote_characters=(arg0); end
  def self.basic_word_break_characters; end
  def self.basic_word_break_characters=(arg0); end
  def self.completer_quote_characters; end
  def self.completer_quote_characters=(arg0); end
  def self.completer_word_break_characters; end
  def self.completer_word_break_characters=(arg0); end
  def self.completion_append_character; end
  def self.completion_append_character=(arg0); end
  def self.completion_case_fold; end
  def self.completion_case_fold=(arg0); end
  def self.completion_proc; end
  def self.completion_proc=(arg0); end
  def self.completion_quote_character; end
  def self.delete_text(*arg0); end
  def self.emacs_editing_mode; end
  def self.emacs_editing_mode?; end
  def self.filename_quote_characters; end
  def self.filename_quote_characters=(arg0); end
  def self.get_screen_size; end
  def self.input=(arg0); end
  def self.insert_text(arg0); end
  def self.line_buffer; end
  def self.output=(arg0); end
  def self.point; end
  def self.point=(arg0); end
  def self.pre_input_hook; end
  def self.pre_input_hook=(arg0); end
  def self.quoting_detection_proc; end
  def self.quoting_detection_proc=(arg0); end
  def self.readline(*arg0); end
  def self.redisplay; end
  def self.refresh_line; end
  def self.set_screen_size(arg0, arg1); end
  def self.special_prefixes; end
  def self.special_prefixes=(arg0); end
  def self.vi_editing_mode; end
  def self.vi_editing_mode?; end
end
