# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby2_keywords/all/ruby2_keywords.rbi
#
# ruby2_keywords-0.0.5

class Module
end
class Proc
end
