# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/slack-ruby-client/all/slack-ruby-client.rbi
#
# slack-ruby-client-0.17.0

module Slack
  def self.config; end
  def self.configure; end
end
class Slack::Logger < Logger
  def self.default; end
end
module Slack::Config
  def logger; end
  def logger=(arg0); end
  def reset; end
  def token; end
  def token=(arg0); end
  extend Slack::Config
end
module Slack::Messages
end
class Slack::Messages::Message < Hashie::Mash
  def log_built_in_message(*arg0); end
  def to_s; end
end
module Slack::Messages::Formatting
  def self.unescape(message); end
end
module Slack::Web
  def self.config; end
  def self.configure; end
end
module Slack::Web::Config
  def adapter; end
  def adapter=(arg0); end
  def ca_file; end
  def ca_file=(arg0); end
  def ca_path; end
  def ca_path=(arg0); end
  def default_max_retries; end
  def default_max_retries=(arg0); end
  def default_page_size; end
  def default_page_size=(arg0); end
  def endpoint; end
  def endpoint=(arg0); end
  def logger; end
  def logger=(arg0); end
  def open_timeout; end
  def open_timeout=(arg0); end
  def proxy; end
  def proxy=(arg0); end
  def reset; end
  def timeout; end
  def timeout=(arg0); end
  def token; end
  def token=(arg0); end
  def user_agent; end
  def user_agent=(arg0); end
  extend Slack::Web::Config
end
module Slack::Web::Api
end
module Slack::Web::Api::Errors
end
class Slack::Web::Api::Errors::SlackError < Faraday::Error
  def error; end
  def errors; end
  def initialize(message, response = nil); end
  def response; end
  def response_metadata; end
end
class Slack::Web::Api::Errors::TooManyRequestsError < Faraday::Error
  def initialize(response); end
  def message; end
  def response; end
  def retry_after; end
end
class Slack::Web::Api::Errors::Accesslimited < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AccountInactive < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AdminUnauthorized < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyArchived < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyInChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyInTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyInTeamInvitedUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyInvited < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyPinned < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyProcessed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyReacted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AlreadyStarred < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AppManagementAppNotInstalledOnOrg < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AppMissingActionUrl < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AppRestrictedOrgWide < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AsUserNotSupported < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AuthedUserNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::AutoProvisionFailure < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadClientSecret < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadHandle < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadImage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadRedirectUri < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadTimestamp < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadTitle < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadToken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadUrl < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BadUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BarrierAlreadyExists < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BarrierNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BarrieredFromUsergroupsNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BotNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BotsNotAllowed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::BotsNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddBot < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddMoreChannelsToGroup < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddMoreGroupsToChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddOthers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddOthersRecurring < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAddSlackbot < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotAuthUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotCompleteOthers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotCompleteRecurring < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotCreateDialog < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotFindChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotFindMessage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotFindService < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotInstallAnOrgInstalledApp < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotInvalidatePrimaryOwner < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotModifyPrimaryOwner < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotMoveLocalChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotParse < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotParseAttachment < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotPrompt < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotResetBot < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotResetPrimaryOwner < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotUnfurlMessage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotUnfurlUrl < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CannotUpdateAdminUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantArchiveGeneral < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantDelete < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantDeleteFile < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantDeleteMessage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantInvite < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantInviteSelf < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantKickFromGeneral < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantKickSelf < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantLeaveGeneral < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CantUpdateMessage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ChannelCannotBeUnshared < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ChannelIsNotPrivate < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ChannelNotArchived < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ChannelNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ChannelTypeNotSupported < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ClientIdTokenMismatch < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CodeAlreadyUsed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ComplianceExportsPreventDeletion < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotArchiveChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotConvertChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotCreateChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotCreateWorkspace < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotDeleteChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotGetConversationPrefs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotGetRetention < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotGetTeams < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotRemoveRetention < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotRenameChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotSetChannelPref < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotSetRetention < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotSetTeamsForChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::CouldNotUnarchiveChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DataNotAvailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DefaultChannelRestricted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DefaultOrgWideChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DeprecatedEndpoint < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DescriptionTooLong < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DiscoverabilitySettingInvalid < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DomainTaken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DuplicateChannelNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DuplicateExternalId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::DuplicateMessageNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EditWindowClosed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EkmAccessDenied < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EmailTaken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EmojiLimitReached < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EmojiNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EnterpriseIsRestricted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::EnterpriseNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorBadFormat < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorBadNameI18n < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorBadUpload < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorBadWide < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorInvalidAlias < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorInvalidEmojiToRename < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorMissingName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorNameTaken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorNameTakenI18n < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorNoImage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ErrorTooBig < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ExternalChannelMigrating < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ExternallySharedOrDisconnectedChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailToGetTeamsForRestrictedUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedForSomeUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedLookingUpUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedSendingDialog < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToAddEmoji < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToAliasEmoji < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToFetchActiveTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToFetchInfo < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToRemoveGroupUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToRemoveUserFromWorkspace < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToRenameEmoji < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSendInvite < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetDefaultChannels < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetDescription < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetDiscoverability < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetExpiration < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetIcon < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetUserToAdmin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetUserToOwner < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToSetUserToRegular < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToUnlinkChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToValidateCaller < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToValidateChannels < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToValidateCustomMessage < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToValidateExpiration < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailedToValidateTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FailureRemovingEmoji < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FatalError < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FeatureNotEnabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FetchMembersFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileCommentNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileDeleted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileDeletingDisabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileNotShared < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileNotYetAvailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::FileUnderReview < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ForbiddenHandle < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ForbiddenTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::GroupAlreadyLinkedToChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::GroupMustNotBeEmpty < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::GroupNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::HandleAlreadyExists < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::HashConflict < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InactiveCall < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InsecureRequest < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InternalError < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidActor < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidAppId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidArgName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidArgs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidArguments < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidArrayArg < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidAttachments < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidAuth < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidBlocks < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidCallId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidChannelId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidChannelType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidChannelsLimit < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidCharset < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidClientId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidCode < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidCreatedBy < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidCursor < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidDate < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidDuration < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidEmail < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidEventContext < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidExternalId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidFormData < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidGrantType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidInputs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidLimit < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidNameMaxlength < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidNamePunctuation < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidNameRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidNameSpecials < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidOutputs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidPayload < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidPermissions < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidPostType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidPresence < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidProfile < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidRequest < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidRequestId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidRestrictedSubjects < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidRoleForUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidScheduledMessageId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidScope < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidScopes < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidSearchChannelType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidSort < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidSortDir < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidStartTime < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidStepStatus < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTargetTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTeamIds < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTime < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTimestamp < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidToken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTrigger < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTsLatest < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTsOldest < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidTypes < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUnfurlsFormat < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUrl < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUserCombination < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUserId < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvalidUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvitedUserNotCreated < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InvitedUserNotReactivated < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::InviteeCantSeeChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::IsArchived < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::IsBot < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::IsInactive < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::LastMember < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::LimitRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::LinkNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MemberAnalyticsDisabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MessageNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MetadataNotAvailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MetadataOnlyDoesNotSupportDate < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MethodDeprecated < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MethodNotSupportedForChannelType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MigrationInProgress < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingArgs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingArgument < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingDialog < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingDuration < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingPostType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingResource < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingScope < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingSubteamName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingTrigger < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingTs < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingUnfurls < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MissingUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MixedScope < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MsgTooLong < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MustProvideTeamDomain < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::MustProvideTeamName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NameAlreadyExists < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NameTaken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NameTakenInOrg < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoActiveSessions < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoAliasSelected < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoBotUserForApp < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoImageUploaded < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoItemSpecified < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoLocalUserOnTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoPermission < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoPin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoReaction < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoResolutionFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoScopes < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoSuchSubteam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoTeamIdsGiven < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoText < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoUser < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoUserProvided < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NoUsersProvided < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAdmin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAllowed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAllowedForGridWorkspace < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAllowedTokenType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAnAdmin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAnEnterprise < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAppAdmin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotArchived < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAuthed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotAuthorized < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotBearerToken < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotEnabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotEnoughUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotEnterpriseTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotImplemented < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotInChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotInDnd < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotPinnable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotPinned < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotReactable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotStarred < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::NotSupported < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OauthAuthorizationUrlMismatch < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OneOrMoreInvalidChannels < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OrgLevelEmailDisplayDisabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OrgLoginRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OrgNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OrgUserNotInTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::OverPaginationLimit < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PaginationNotAvailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PaidOnly < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PaidTeamsOnly < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PermissionDenied < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PlanUpgradeRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PostingToGeneralChannelDenied < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PreviewFeatureNotAvailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PrimaryUsergroupNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ProfileSetFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PublicVideoNotAllowed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::PushLimitReached < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RateLimited < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::Ratelimited < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RequestAlreadyResolved < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RequestIdOrAppIdIsRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RequestIdRequiredForCustomIntegrations < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RequestTimeout < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ReservedName < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ResizedButStillTooLarge < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RestrictedAction < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RestrictedActionNonThreadableChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RestrictedActionReadOnlyChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RestrictedActionThreadOnlyChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RetentionOverrideNotAllowed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::RtmConnectRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SentRecently < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ServiceUnavailable < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SessionExpired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SessionInvalidationFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SessionNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SlackConnectBlockedFileType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SlackConnectFileLinkSharingBlocked < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SlackConnectFileUploadSharingBlocked < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SnoozeEndFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SnoozeFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SnoozeNotActive < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::SubteamMaxUsersExceeded < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TeamAccessNotGranted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TeamAddedToOrg < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TeamIdOrOrgRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TeamNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TeamNotOnEnterprise < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ThreadNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TimeInPast < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TimeTooFar < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TokenRevoked < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooLarge < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooLong < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyAttachments < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyConvosForAppOnTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyConvosForTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyEmoji < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyFrames < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyIds < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyIdsProvided < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyLinkedChannels < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyMembers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyPins < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyReactions < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyTargetTeams < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyTeamsProvided < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TooManyUsers < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TriggerExchanged < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TriggerExpired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::TwoFactorSetupRequired < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnableToLeaveLastTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnableToLinkIdpGroupAndChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnableToUnlinkIdpGroupAndChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnknownMethod < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnknownType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnsupportedArguments < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnsupportedContextType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UnsupportedTeamType < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UpdateFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UraMaxChannels < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserAlreadyDeleted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserAlreadyTeamMember < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserDisabled < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserDoesNotOwnChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserIsAlreadyDeleted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserIsBot < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserIsNotAGuest < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserIsRestricted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserIsUltraRestricted < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserMustBeAdmin < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserNotInChannel < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserNotVisible < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UserSessionResetFailed < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UsergroupNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UsergroupNotLinkedToTeam < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UsergroupTeamNotProvisioned < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UsersListNotSupplied < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::UsersNotFound < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ValidationErrors < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ViewTooLarge < Slack::Web::Api::Errors::SlackError
end
class Slack::Web::Api::Errors::ServerError < Slack::Web::Api::Errors::InternalError
end
class Slack::Web::Api::Errors::ParsingError < Slack::Web::Api::Errors::ServerError
end
class Slack::Web::Api::Errors::HttpRequestError < Slack::Web::Api::Errors::ServerError
end
class Slack::Web::Api::Errors::TimeoutError < Slack::Web::Api::Errors::HttpRequestError
end
class Slack::Web::Api::Errors::UnavailableError < Slack::Web::Api::Errors::HttpRequestError
end
module Slack::Web::Faraday
end
module Slack::Web::Faraday::Response
end
class Slack::Web::Faraday::Response::RaiseError < Faraday::Response::Middleware
  def call(env); end
  def on_complete(env); end
end
class Slack::Web::Faraday::Response::WrapError < Faraday::Response::Middleware
  def call(env); end
  def on_complete(env); end
end
module Slack::Web::Faraday::Connection
  def connection; end
end
module Slack::Web::Faraday::Request
  def delete(path, options = nil); end
  def get(path, options = nil); end
  def post(path, options = nil); end
  def put(path, options = nil); end
  def request(method, path, options); end
end
module Slack::Web::Api::Mixins
end
module Slack::Web::Api::Mixins::Ids
  def id_for(key, name, prefix, enum_method, list_method, not_found_error); end
end
module Slack::Web::Api::Mixins::Channels
  def channels_id(options = nil); end
  include Slack::Web::Api::Mixins::Ids
end
module Slack::Web::Api::Mixins::Conversations
  def conversations_id(options = nil); end
  include Slack::Web::Api::Mixins::Ids
end
module Slack::Web::Api::Mixins::Users
  def users_id(options = nil); end
  include Slack::Web::Api::Mixins::Ids
end
module Slack::Web::Api::Mixins::Groups
  def groups_id(options = nil); end
  include Slack::Web::Api::Mixins::Ids
end
module Slack::Web::Api::Endpoints
  include Slack::Web::Api::Endpoints::AdminAnalytics
  include Slack::Web::Api::Endpoints::AdminApps
  include Slack::Web::Api::Endpoints::AdminAppsApproved
  include Slack::Web::Api::Endpoints::AdminAppsRequests
  include Slack::Web::Api::Endpoints::AdminAppsRestricted
  include Slack::Web::Api::Endpoints::AdminBarriers
  include Slack::Web::Api::Endpoints::AdminConversations
  include Slack::Web::Api::Endpoints::AdminConversationsEkm
  include Slack::Web::Api::Endpoints::AdminConversationsRestrictaccess
  include Slack::Web::Api::Endpoints::AdminEmoji
  include Slack::Web::Api::Endpoints::AdminInviterequests
  include Slack::Web::Api::Endpoints::AdminInviterequestsApproved
  include Slack::Web::Api::Endpoints::AdminInviterequestsDenied
  include Slack::Web::Api::Endpoints::AdminTeams
  include Slack::Web::Api::Endpoints::AdminTeamsAdmins
  include Slack::Web::Api::Endpoints::AdminTeamsOwners
  include Slack::Web::Api::Endpoints::AdminTeamsSettings
  include Slack::Web::Api::Endpoints::AdminUsergroups
  include Slack::Web::Api::Endpoints::AdminUsers
  include Slack::Web::Api::Endpoints::AdminUsersSession
  include Slack::Web::Api::Endpoints::Api
  include Slack::Web::Api::Endpoints::Apps
  include Slack::Web::Api::Endpoints::AppsConnections
  include Slack::Web::Api::Endpoints::AppsEventAuthorizations
  include Slack::Web::Api::Endpoints::AppsPermissions
  include Slack::Web::Api::Endpoints::AppsPermissionsResources
  include Slack::Web::Api::Endpoints::AppsPermissionsScopes
  include Slack::Web::Api::Endpoints::AppsPermissionsUsers
  include Slack::Web::Api::Endpoints::Auth
  include Slack::Web::Api::Endpoints::AuthTeams
  include Slack::Web::Api::Endpoints::Bots
  include Slack::Web::Api::Endpoints::Calls
  include Slack::Web::Api::Endpoints::CallsParticipants
  include Slack::Web::Api::Endpoints::Channels
  include Slack::Web::Api::Endpoints::Chat
  include Slack::Web::Api::Endpoints::ChatScheduledmessages
  include Slack::Web::Api::Endpoints::Conversations
  include Slack::Web::Api::Endpoints::Dialog
  include Slack::Web::Api::Endpoints::Dnd
  include Slack::Web::Api::Endpoints::Emoji
  include Slack::Web::Api::Endpoints::Files
  include Slack::Web::Api::Endpoints::FilesComments
  include Slack::Web::Api::Endpoints::FilesRemote
  include Slack::Web::Api::Endpoints::Groups
  include Slack::Web::Api::Endpoints::Im
  include Slack::Web::Api::Endpoints::Migration
  include Slack::Web::Api::Endpoints::Mpim
  include Slack::Web::Api::Endpoints::Oauth
  include Slack::Web::Api::Endpoints::OauthV2
  include Slack::Web::Api::Endpoints::Pins
  include Slack::Web::Api::Endpoints::Reactions
  include Slack::Web::Api::Endpoints::Reminders
  include Slack::Web::Api::Endpoints::Rtm
  include Slack::Web::Api::Endpoints::Search
  include Slack::Web::Api::Endpoints::Stars
  include Slack::Web::Api::Endpoints::Team
  include Slack::Web::Api::Endpoints::TeamProfile
  include Slack::Web::Api::Endpoints::Usergroups
  include Slack::Web::Api::Endpoints::UsergroupsUsers
  include Slack::Web::Api::Endpoints::Users
  include Slack::Web::Api::Endpoints::UsersAdmin
  include Slack::Web::Api::Endpoints::UsersPrefs
  include Slack::Web::Api::Endpoints::UsersProfile
  include Slack::Web::Api::Endpoints::Views
  include Slack::Web::Api::Endpoints::Workflows
  include Slack::Web::Api::Mixins::Channels
  include Slack::Web::Api::Mixins::Conversations
  include Slack::Web::Api::Mixins::Groups
  include Slack::Web::Api::Mixins::Users
end
module Slack::Web::Api::Endpoints::AdminAnalytics
  def admin_analytics_getFile(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminApps
  def admin_apps_approve(options = nil); end
  def admin_apps_clearResolution(options = nil); end
  def admin_apps_restrict(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminAppsApproved
  def admin_apps_approved_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminAppsRequests
  def admin_apps_requests_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminAppsRestricted
  def admin_apps_restricted_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminBarriers
  def admin_barriers_create(options = nil); end
  def admin_barriers_delete(options = nil); end
  def admin_barriers_list(options = nil); end
  def admin_barriers_update(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminConversations
  def admin_conversations_archive(options = nil); end
  def admin_conversations_convertToPrivate(options = nil); end
  def admin_conversations_create(options = nil); end
  def admin_conversations_delete(options = nil); end
  def admin_conversations_getConversationPrefs(options = nil); end
  def admin_conversations_getCustomRetention(options = nil); end
  def admin_conversations_getTeams(options = nil); end
  def admin_conversations_invite(options = nil); end
  def admin_conversations_removeCustomRetention(options = nil); end
  def admin_conversations_rename(options = nil); end
  def admin_conversations_search(options = nil); end
  def admin_conversations_setConversationPrefs(options = nil); end
  def admin_conversations_setCustomRetention(options = nil); end
  def admin_conversations_setTeams(options = nil); end
  def admin_conversations_unarchive(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminConversationsEkm
  def admin_conversations_ekm_listOriginalConnectedChannelInfo(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminConversationsRestrictaccess
  def admin_conversations_restrictAccess_addGroup(options = nil); end
  def admin_conversations_restrictAccess_listGroups(options = nil); end
  def admin_conversations_restrictAccess_removeGroup(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminEmoji
  def admin_emoji_add(options = nil); end
  def admin_emoji_addAlias(options = nil); end
  def admin_emoji_list(options = nil); end
  def admin_emoji_remove(options = nil); end
  def admin_emoji_rename(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminInviterequests
  def admin_inviteRequests_approve(options = nil); end
  def admin_inviteRequests_deny(options = nil); end
  def admin_inviteRequests_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminInviterequestsApproved
  def admin_inviteRequests_approved_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminInviterequestsDenied
  def admin_inviteRequests_denied_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminTeams
  def admin_teams_create(options = nil); end
  def admin_teams_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminTeamsAdmins
  def admin_teams_admins_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminTeamsOwners
  def admin_teams_owners_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminTeamsSettings
  def admin_teams_settings_info(options = nil); end
  def admin_teams_settings_setDefaultChannels(options = nil); end
  def admin_teams_settings_setDescription(options = nil); end
  def admin_teams_settings_setDiscoverability(options = nil); end
  def admin_teams_settings_setIcon(options = nil); end
  def admin_teams_settings_setName(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminUsergroups
  def admin_usergroups_addChannels(options = nil); end
  def admin_usergroups_addTeams(options = nil); end
  def admin_usergroups_listChannels(options = nil); end
  def admin_usergroups_removeChannels(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminUsers
  def admin_users_assign(options = nil); end
  def admin_users_invite(options = nil); end
  def admin_users_list(options = nil); end
  def admin_users_remove(options = nil); end
  def admin_users_setAdmin(options = nil); end
  def admin_users_setExpiration(options = nil); end
  def admin_users_setOwner(options = nil); end
  def admin_users_setRegular(options = nil); end
end
module Slack::Web::Api::Endpoints::AdminUsersSession
  def admin_users_session_invalidate(options = nil); end
  def admin_users_session_list(options = nil); end
  def admin_users_session_reset(options = nil); end
end
module Slack::Web::Api::Endpoints::Api
  def api_test(options = nil); end
end
module Slack::Web::Api::Endpoints::Apps
  def apps_uninstall(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsConnections
  def apps_connections_open(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsEventAuthorizations
  def apps_event_authorizations_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsPermissions
  def apps_permissions_info(options = nil); end
  def apps_permissions_request(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsPermissionsResources
  def apps_permissions_resources_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsPermissionsScopes
  def apps_permissions_scopes_list(options = nil); end
end
module Slack::Web::Api::Endpoints::AppsPermissionsUsers
  def apps_permissions_users_list(options = nil); end
  def apps_permissions_users_request(options = nil); end
end
module Slack::Web::Api::Endpoints::Auth
  def auth_revoke(options = nil); end
  def auth_test(options = nil); end
end
module Slack::Web::Api::Endpoints::AuthTeams
  def auth_teams_list(options = nil); end
end
module Slack::Web::Api::Endpoints::Bots
  def bots_info(options = nil); end
end
module Slack::Web::Api::Endpoints::Calls
  def calls_add(options = nil); end
  def calls_end(options = nil); end
  def calls_info(options = nil); end
  def calls_update(options = nil); end
end
module Slack::Web::Api::Endpoints::CallsParticipants
  def calls_participants_add(options = nil); end
  def calls_participants_remove(options = nil); end
end
module Slack::Web::Api::Endpoints::Channels
  def channels_delete(options = nil); end
end
module Slack::Web::Api::Endpoints::Chat
  def chat_command(options = nil); end
  def chat_delete(options = nil); end
  def chat_deleteScheduledMessage(options = nil); end
  def chat_getPermalink(options = nil); end
  def chat_meMessage(options = nil); end
  def chat_postEphemeral(options = nil); end
  def chat_postMessage(options = nil); end
  def chat_scheduleMessage(options = nil); end
  def chat_unfurl(options = nil); end
  def chat_update(options = nil); end
end
module Slack::Web::Api::Endpoints::ChatScheduledmessages
  def chat_scheduledMessages_list(options = nil); end
end
module Slack::Web::Api::Endpoints::Conversations
  def conversations_archive(options = nil); end
  def conversations_close(options = nil); end
  def conversations_create(options = nil); end
  def conversations_history(options = nil); end
  def conversations_info(options = nil); end
  def conversations_invite(options = nil); end
  def conversations_join(options = nil); end
  def conversations_kick(options = nil); end
  def conversations_leave(options = nil); end
  def conversations_list(options = nil); end
  def conversations_mark(options = nil); end
  def conversations_members(options = nil); end
  def conversations_open(options = nil); end
  def conversations_rename(options = nil); end
  def conversations_replies(options = nil); end
  def conversations_setPurpose(options = nil); end
  def conversations_setTopic(options = nil); end
  def conversations_unarchive(options = nil); end
end
module Slack::Web::Api::Endpoints::Dialog
  def dialog_open(options = nil); end
end
module Slack::Web::Api::Endpoints::Dnd
  def dnd_endDnd(options = nil); end
  def dnd_endSnooze(options = nil); end
  def dnd_info(options = nil); end
  def dnd_setSnooze(options = nil); end
  def dnd_teamInfo(options = nil); end
end
module Slack::Web::Api::Endpoints::Emoji
  def emoji_list(options = nil); end
end
module Slack::Web::Api::Endpoints::Files
  def files_delete(options = nil); end
  def files_edit(options = nil); end
  def files_info(options = nil); end
  def files_list(options = nil); end
  def files_revokePublicURL(options = nil); end
  def files_share(options = nil); end
  def files_sharedPublicURL(options = nil); end
  def files_upload(options = nil); end
end
module Slack::Web::Api::Endpoints::FilesComments
  def files_comments_delete(options = nil); end
end
module Slack::Web::Api::Endpoints::FilesRemote
  def files_remote_add(options = nil); end
  def files_remote_info(options = nil); end
  def files_remote_list(options = nil); end
  def files_remote_remove(options = nil); end
  def files_remote_share(options = nil); end
  def files_remote_update(options = nil); end
end
module Slack::Web::Api::Endpoints::Groups
end
module Slack::Web::Api::Endpoints::Im
end
module Slack::Web::Api::Endpoints::Migration
  def migration_exchange(options = nil); end
end
module Slack::Web::Api::Endpoints::Mpim
end
module Slack::Web::Api::Endpoints::Oauth
  def oauth_access(options = nil); end
  def oauth_token(options = nil); end
end
module Slack::Web::Api::Endpoints::OauthV2
  def oauth_v2_access(options = nil); end
end
module Slack::Web::Api::Endpoints::Pins
  def pins_add(options = nil); end
  def pins_list(options = nil); end
  def pins_remove(options = nil); end
end
module Slack::Web::Api::Endpoints::Reactions
  def reactions_add(options = nil); end
  def reactions_get(options = nil); end
  def reactions_list(options = nil); end
  def reactions_remove(options = nil); end
end
module Slack::Web::Api::Endpoints::Reminders
  def reminders_add(options = nil); end
  def reminders_complete(options = nil); end
  def reminders_delete(options = nil); end
  def reminders_info(options = nil); end
  def reminders_list(options = nil); end
end
module Slack::Web::Api::Endpoints::Rtm
  def rtm_connect(options = nil); end
  def rtm_start(options = nil); end
end
module Slack::Web::Api::Endpoints::Search
  def search_all(options = nil); end
  def search_files(options = nil); end
  def search_messages(options = nil); end
end
module Slack::Web::Api::Endpoints::Stars
  def stars_add(options = nil); end
  def stars_list(options = nil); end
  def stars_remove(options = nil); end
end
module Slack::Web::Api::Endpoints::Team
  def team_accessLogs(options = nil); end
  def team_billableInfo(options = nil); end
  def team_info(options = nil); end
  def team_integrationLogs(options = nil); end
end
module Slack::Web::Api::Endpoints::TeamProfile
  def team_profile_get(options = nil); end
end
module Slack::Web::Api::Endpoints::Usergroups
  def usergroups_create(options = nil); end
  def usergroups_disable(options = nil); end
  def usergroups_enable(options = nil); end
  def usergroups_list(options = nil); end
  def usergroups_update(options = nil); end
end
module Slack::Web::Api::Endpoints::UsergroupsUsers
  def usergroups_users_list(options = nil); end
  def usergroups_users_update(options = nil); end
end
module Slack::Web::Api::Endpoints::Users
  def users_conversations(options = nil); end
  def users_deletePhoto(options = nil); end
  def users_getPresence(options = nil); end
  def users_identity(options = nil); end
  def users_info(options = nil); end
  def users_list(options = nil); end
  def users_lookupByEmail(options = nil); end
  def users_setActive(options = nil); end
  def users_setPhoto(options = nil); end
  def users_setPresence(options = nil); end
end
module Slack::Web::Api::Endpoints::UsersAdmin
  def users_admin_invite(options = nil); end
  def users_admin_setInactive(options = nil); end
end
module Slack::Web::Api::Endpoints::UsersPrefs
  def users_prefs_get(options = nil); end
end
module Slack::Web::Api::Endpoints::UsersProfile
  def users_profile_get(options = nil); end
  def users_profile_set(options = nil); end
end
module Slack::Web::Api::Endpoints::Views
  def views_open(options = nil); end
  def views_publish(options = nil); end
  def views_push(options = nil); end
  def views_update(options = nil); end
end
module Slack::Web::Api::Endpoints::Workflows
  def workflows_stepCompleted(options = nil); end
  def workflows_stepFailed(options = nil); end
  def workflows_updateStep(options = nil); end
end
module Slack::Web::Api::Pagination
end
class Slack::Web::Api::Pagination::Cursor
  def client; end
  def each; end
  def initialize(client, verb, params = nil); end
  def max_retries; end
  def params; end
  def sleep_interval; end
  def verb; end
  include Enumerable
end
class Slack::Web::Client
  def adapter; end
  def adapter=(arg0); end
  def ca_file; end
  def ca_file=(arg0); end
  def ca_path; end
  def ca_path=(arg0); end
  def default_max_retries; end
  def default_max_retries=(arg0); end
  def default_page_size; end
  def default_page_size=(arg0); end
  def endpoint; end
  def endpoint=(arg0); end
  def initialize(options = nil); end
  def logger; end
  def logger=(arg0); end
  def open_timeout; end
  def open_timeout=(arg0); end
  def proxy; end
  def proxy=(arg0); end
  def self.config; end
  def self.configure; end
  def timeout; end
  def timeout=(arg0); end
  def token; end
  def token=(arg0); end
  def user_agent; end
  def user_agent=(arg0); end
  include Slack::Web::Api::Endpoints
  include Slack::Web::Faraday::Connection
  include Slack::Web::Faraday::Request
end
module Slack::RealTime
  def self.config; end
  def self.configure; end
end
module Slack::RealTime::Concurrency
end
class Slack::RealTime::Socket
  def addr; end
  def close; end
  def connect!; end
  def connect; end
  def connected?; end
  def current_time; end
  def disconnect!; end
  def driver; end
  def initialize(url, options = nil); end
  def logger; end
  def options; end
  def options=(arg0); end
  def port; end
  def restart_async(_client, _url); end
  def secure?; end
  def send_data(message); end
  def start_async(_client); end
  def start_sync(client); end
  def time_since_last_message; end
  def url; end
  def url=(arg0); end
end
module Slack::RealTime::Api
end
module Slack::RealTime::Api::MessageId
  def next_id; end
end
module Slack::RealTime::Api::Ping
  def ping(options = nil); end
end
module Slack::RealTime::Api::Message
  def message(options = nil); end
end
module Slack::RealTime::Api::Typing
  def typing(options = nil); end
end
module Slack::RealTime::Models
end
class Slack::RealTime::Models::Base < Hashie::Mash
  def log_built_in_message(*arg0); end
end
class Slack::RealTime::Models::User < Slack::RealTime::Models::Base
end
class Slack::RealTime::Models::Bot < Slack::RealTime::Models::Base
end
class Slack::RealTime::Models::Channel < Slack::RealTime::Models::Base
end
class Slack::RealTime::Models::Group < Slack::RealTime::Models::Base
end
class Slack::RealTime::Models::Team < Slack::RealTime::Models::Base
end
class Slack::RealTime::Models::Im < Slack::RealTime::Models::Base
end
module Slack::RealTime::Stores
end
class Slack::RealTime::Stores::Base
  def bots; end
  def bots=(arg0); end
  def channels; end
  def channels=(arg0); end
  def groups; end
  def groups=(arg0); end
  def ims; end
  def ims=(arg0); end
  def initialize(_attrs); end
  def self.events; end
  def self.events=(arg0); end
  def self.on(event, &block); end
  def self; end
  def team; end
  def teams; end
  def teams=(arg0); end
  def users; end
  def users=(arg0); end
end
class Slack::RealTime::Stores::Starter < Slack::RealTime::Stores::Base
  def initialize(attrs); end
  def self; end
  def team; end
end
class Slack::RealTime::Stores::Store < Slack::RealTime::Stores::Base
  def initialize(attrs); end
  def self; end
  def team; end
end
class Slack::RealTime::Store < Slack::RealTime::Stores::Store
end
module Slack::RealTime::Config
  def concurrency; end
  def concurrency=(arg0); end
  def detect_concurrency; end
  def logger; end
  def logger=(arg0); end
  def reset; end
  def start_method; end
  def start_method=(arg0); end
  def start_options; end
  def start_options=(arg0); end
  def store_class; end
  def store_class=(arg0); end
  def token; end
  def token=(arg0); end
  def websocket_ping; end
  def websocket_ping=(arg0); end
  def websocket_proxy; end
  def websocket_proxy=(arg0); end
  extend Slack::RealTime::Config
end
class Slack::RealTime::Config::NoConcurrencyError < StandardError
end
class Slack::RealTime::Client
  def bots; end
  def build_socket; end
  def callback(event, type); end
  def callbacks; end
  def channels; end
  def close(_event); end
  def concurrency; end
  def concurrency=(arg0); end
  def dispatch(event); end
  def groups; end
  def ims; end
  def initialize(options = nil); end
  def keep_alive?; end
  def logger; end
  def logger=(arg0); end
  def on(type, &block); end
  def open_event(_event); end
  def restart_async; end
  def rtm_start_method; end
  def run_callbacks(type, data); end
  def run_handlers(type, data); end
  def run_loop; end
  def run_ping!; end
  def run_ping?; end
  def self.config; end
  def self.configure; end
  def self.events; end
  def self.events=(arg0); end
  def self; end
  def send_json(data); end
  def socket_class; end
  def socket_options; end
  def start!(&block); end
  def start_async(&block); end
  def start_method; end
  def start_method=(arg0); end
  def start_options; end
  def start_options=(arg0); end
  def started?; end
  def stop!; end
  def store; end
  def store=(arg0); end
  def store_class; end
  def store_class=(arg0); end
  def team; end
  def teams; end
  def to_s; end
  def token; end
  def token=(arg0); end
  def url; end
  def url=(arg0); end
  def users; end
  def web_client; end
  def web_client=(arg0); end
  def websocket_ping; end
  def websocket_ping=(arg0); end
  def websocket_ping_timer; end
  def websocket_proxy; end
  def websocket_proxy=(arg0); end
  include Slack::RealTime::Api::Message
  include Slack::RealTime::Api::MessageId
  include Slack::RealTime::Api::Ping
  include Slack::RealTime::Api::Typing
end
class Slack::RealTime::Client::ClientNotStartedError < StandardError
end
class Slack::RealTime::Client::ClientAlreadyStartedError < StandardError
end
module Slack::Events
  def self.config; end
  def self.configure; end
end
module Slack::Events::Config
  def reset; end
  def signature_expires_in; end
  def signature_expires_in=(arg0); end
  def signing_secret; end
  def signing_secret=(arg0); end
  extend Slack::Events::Config
end
class Slack::Events::Request
  def body; end
  def expired?; end
  def http_request; end
  def initialize(http_request, options = nil); end
  def signature; end
  def signature_expires_in; end
  def signing_secret; end
  def timestamp; end
  def valid?; end
  def verify!; end
  def version; end
end
class Slack::Events::Request::MissingSigningSecret < StandardError
end
class Slack::Events::Request::TimestampExpired < StandardError
end
class Slack::Events::Request::InvalidSignature < StandardError
end
