# Generated by Django 2.2.9 on 2020-04-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.TextField(unique=True, verbose_name='Install-specific app ID')),
                ('authed_user_id', models.TextField(verbose_name='Installing user ID')),
                ('scope', models.TextField(verbose_name='OAuth scopes granted')),
                ('access_token', models.TextField(verbose_name='OAuth access token')),
                ('bot_user_id', models.TextField(verbose_name='Install-specific bot ID')),
                ('team_name', models.TextField(verbose_name='Workspace name')),
                ('team_id', models.TextField(verbose_name='Workspace ID')),
            ],
        ),
    ]
