# Generated by Django 2.2.10 on 2020-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='app_id',
            field=models.TextField(verbose_name='Install-specific app ID'),
        ),
        migrations.AlterField(
            model_name='install',
            name='team_id',
            field=models.TextField(unique=True, verbose_name='Workspace ID'),
        ),
        migrations.AddIndex(
            model_name='install',
            index=models.Index(fields=['team_id'], name='slackbot_in_team_id_9e5616_idx'),
        ),
    ]
