# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpm_id', models.CharField(max_length=200, verbose_name='Google Play Music ID')),
                ('spotify_id', models.CharField(max_length=200, verbose_name='Spotify ID')),
                ('apple_id', models.CharField(max_length=200, verbose_name='Apple Music ID')),
                ('soundcloud_id', models.CharField(max_length=200, verbose_name='Soundcloud ID')),
                ('match_rating', models.IntegerField(default=0, verbose_name='Rating of the match')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpm_id', models.CharField(max_length=200, verbose_name='Google Play Music ID')),
                ('spotify_id', models.CharField(max_length=200, verbose_name='Spotify ID')),
                ('apple_id', models.CharField(max_length=200, verbose_name='Apple Music ID')),
                ('soundcloud_id', models.CharField(max_length=200, verbose_name='Soundcloud ID')),
                ('match_rating', models.IntegerField(default=0, verbose_name='Rating of the match')),
            ],
        ),
    ]
