# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='insertion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of initial insertion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of last update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='insertion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of initial insertion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of last update'),
            preserve_default=False,
        ),
    ]
