# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0002_auto_20171113_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=200, verbose_name='Artist Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Album Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='', max_length=200, verbose_name='Artist Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artwork',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Track Name'),
            preserve_default=False,
        ),
    ]
