# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0004_auto_20171219_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='insertion_date',
        ),
        migrations.RemoveField(
            model_name='music',
            name='update_date',
        ),
    ]
