# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0005_auto_20171220_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='apple_url',
            field=models.URLField(blank=True, verbose_name='Apple Music URL'),
        ),
        migrations.AlterField(
            model_name='music',
            name='gpm_url',
            field=models.URLField(blank=True, verbose_name='Google Play Music URL'),
        ),
        migrations.AlterField(
            model_name='music',
            name='soundcloud_url',
            field=models.URLField(blank=True, verbose_name='Soundcloud URL'),
        ),
        migrations.AlterField(
            model_name='music',
            name='spotify_url',
            field=models.URLField(blank=True, verbose_name='Spotify URL'),
        ),
    ]
