# Generated by Django 2.1.5 on 2019-01-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0009_formsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(null=True, verbose_name="Client's user agent")),
                ('ip_address', models.CharField(max_length=45, null=True, verbose_name="Client's IP address")),
                ('referer', models.URLField(null=True, verbose_name='HTTP referer')),
                ('music_id', models.IntegerField(verbose_name='Id accessed')),
            ],
        ),
    ]
