# Generated by Django 2.1.5 on 2019-01-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0010_musicaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(null=True, verbose_name="Client's user agent")),
                ('ip_address', models.CharField(max_length=45, null=True, verbose_name="Client's IP address")),
                ('referer', models.URLField(null=True, verbose_name='HTTP referer')),
                ('link', models.URLField(verbose_name='The web address of the link clicked')),
                ('link_type', models.CharField(choices=[('apple', 'Apple Music'), ('gpm', 'Google Play Music'), ('soundcloud', 'Soundcloud'), ('spotify', 'Spotify')], max_length=10, verbose_name='Type of link')),
            ],
        ),
    ]
