# Generated by Django 2.1.5 on 2019-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0011_musicclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicclick',
            name='redirect',
            field=models.BooleanField(default=False, verbose_name='Whether or not the redirect checkbox was checked'),
        ),
    ]
