# Generated by Django 2.1.5 on 2019-03-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0012_musicclick_redirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicClick',
        ),
    ]
