# Generated by Django 2.1.5 on 2019-03-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0013_delete_musicclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=254, verbose_name='User inputted email address')),
                ('subject', models.CharField(max_length=78, verbose_name='Email subject')),
                ('body', models.TextField(verbose_name='Email body')),
            ],
        ),
    ]
