# Generated by Django 2.1.5 on 2019-03-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0014_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('from_address', 'subject', 'body')},
        ),
    ]
