# Generated by Django 2.1.7 on 2019-04-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0015_auto_20190315_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
