# Generated by Django 2.1.7 on 2019-08-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatnik', '0016_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tidal_url',
            field=models.URLField(null=True, unique=True, verbose_name='Tidal URL'),
        ),
    ]
